'use strict';
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const finePointer=window.matchMedia('(hover: hover) and (pointer: fine)').matches;
const heroImage=document.querySelector('#hero-image');
const bouquets={
  wild:{name:'Дико влюблён',price:'6 900 ₽',image:'hero.webp',alt:'Яркий букет с розовыми георгинами, розами и синими дельфиниумами',description:'Фуксия, кобальт и вспышки оранжевого. Букет для признания, которое хочется сделать громко. Каждый стебель живёт в своём ритме — и вместе они звучат.',composition:'Георгины, садовые розы, дельфиниум, антуриум и выразительная зелень.',mood:'Смелость, восторг, большое «люблю».',background:'#c4d4ff'},
  soft:{name:'Тихое «люблю»',price:'5 400 ₽',image:'bouquet.webp',alt:'Нежный букет роз и космей в розовой вазе',description:'Пудровые розы, воздушные космеи и немного розового света. Для тихих признаний, искренней благодарности и очень тёплых встреч.',composition:'Садовые розы, ранункулюсы, космея и сезонная зелень. Ваза на фото — вариант оформления.',mood:'Нежность, тепло, забота.',background:'#752845'},
  peony:{name:'Пионовое настроение',price:'7 200 ₽',image:'petals.webp',alt:'Коралловые и розовые пионы крупным планом',description:'Облако пышных пионов в розовых и коралловых оттенках. Для дня, которому хочется добавить цвета, и человека, которому хочется подарить радость.',composition:'Пышные пионы в сезонных оттенках. На фото — детали цветка; состав зависит от сезонности.',mood:'Радость, лёгкость, праздник без повода.',background:'#f5439b'}
};
const moods={love:{word:'Люблю.',quote:'«Ты — моё самое\nкрасивое совпадение».',description:'Смелый букет для чувства, которое сложно спрятать.',bouquet:'wild'},thanks:{word:'Спасибо.',quote:'«Как же хорошо,\nчто ты есть».',description:'Нежные цветы, когда благодарность больше любых слов.',bouquet:'soft'},just:{word:'Просто так.',quote:'«Улыбнись.\nЭто всё тебе».',description:'Пионы для обычного дня, который вдруг стал особенным.',bouquet:'peony'}};
let chosenBouquet=null,currentDialogBouquet='wild',currentMood='love',toastTimer;
const dialog=document.querySelector('#bouquet-dialog');
function animateIn(element,frames,duration=650){if(!reducedMotion)element.animate(frames,{duration,easing:'cubic-bezier(.16,1,.3,1)'});}
function toast(text){const el=document.querySelector('.toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3000);}
function openBouquet(id){const bouquet=bouquets[id];if(!bouquet)return;currentDialogBouquet=id;document.querySelector('#dialog-title').textContent=bouquet.name;document.querySelector('#dialog-description').textContent=bouquet.description;document.querySelector('#dialog-composition').textContent=bouquet.composition;document.querySelector('#dialog-mood').textContent=bouquet.mood;document.querySelector('#dialog-price').textContent=bouquet.price;const image=document.querySelector('#dialog-image');image.src=bouquet.image;image.alt=bouquet.alt;const visual=document.querySelector('.dialog-visual');visual.style.background=bouquet.background;visual.classList.toggle('photo-mode',id!=='wild');if(!dialog.open){dialog.showModal();document.body.style.overflow='hidden';}animateIn(dialog,[{opacity:0,transform:'translateY(35px) scale(.97)'},{opacity:1,transform:'translateY(0) scale(1)'}],450);}
function closeDialog(){dialog.close();document.body.style.overflow='';}
function createIcon(name){
  const ns='http://www.w3.org/2000/svg';
  const svg=document.createElementNS(ns,'svg');
  svg.setAttribute('class','icon icon-'+name);
  svg.setAttribute('viewBox','0 0 32 32');
  svg.setAttribute('aria-hidden','true');
  svg.setAttribute('focusable','false');
  const path=document.createElementNS(ns,'path');
  path.setAttribute('d','M16 5v22M5 16h22');
  path.setAttribute('fill','none');
  path.setAttribute('stroke','currentColor');
  path.setAttribute('stroke-width','1.5');
  path.setAttribute('stroke-linecap','round');
  svg.append(path);
  return svg;
}
function setMood(key){if(!moods[key])return;currentMood=key;const mood=moods[key];const section=document.querySelector('#mood');section.dataset.mood=key;document.querySelectorAll('.mood-chip').forEach(button=>{const active=button.dataset.mood===key;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});document.querySelector('.mood-quote').textContent=mood.quote;document.querySelector('.mood-description').textContent=mood.description;document.querySelector('.mood-stage-word').textContent=mood.word;const view=document.querySelector('#mood-view');view.dataset.open=mood.bouquet;view.replaceChildren(document.createTextNode('Посмотреть «'+bouquets[mood.bouquet].name.replace(/[«»]/g,'')+'»'));const plus=document.createElement('span');plus.setAttribute('aria-hidden','true');plus.append(createIcon('plus'));view.append(plus);const image=document.querySelector('#mood-image');image.src=bouquets[mood.bouquet].image;image.alt=bouquets[mood.bouquet].alt;const stage=document.querySelector('.mood-stage');stage.classList.toggle('photo-mode',key==='thanks');stage.classList.toggle('macro-mode',key==='just');animateIn(document.querySelector('.mood-result'),[{opacity:0,transform:'translateY(15px)'},{opacity:1,transform:'translateY(0)'}],500);animateIn(image,[{opacity:0,scale:'.8',rotate:'-10deg'},{opacity:1,scale:'1',rotate:'0deg'}],700);if(chosenBouquet)document.querySelector('#selection-description').textContent='Настроение: '+mood.word+' Сохрани пожелания для разговора с флористом.';}
function selectBouquet(id){if(!bouquets[id])return;chosenBouquet=id;document.querySelector('#selection-name').textContent=bouquets[id].name+' · '+bouquets[id].price;document.querySelector('#selection-description').textContent='Настроение: '+moods[currentMood].word+' Сохрани пожелания для разговора с флористом.';const summary=document.querySelector('#selection-summary');summary.hidden=false;if(dialog.open)closeDialog();summary.scrollIntoView({behavior:reducedMotion?'instant':'smooth',block:'center'});animateIn(summary,[{opacity:0,transform:'translateY(25px)'},{opacity:1,transform:'translateY(0)'}]);toast('Букет выбран. Добавим к нему твоё настроение.');}
document.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>openBouquet(button.dataset.open)));
document.querySelector('.dialog-close').addEventListener('click',closeDialog);
dialog.addEventListener('close',()=>{document.body.style.overflow='';});
dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)closeDialog();}});
document.querySelector('#select-bouquet').addEventListener('click',()=>selectBouquet(currentDialogBouquet));
document.querySelectorAll('.mood-chip').forEach(button=>button.addEventListener('click',()=>setMood(button.dataset.mood)));
document.querySelector('#save-selection').addEventListener('click',()=>{if(!chosenBouquet)return;const b=bouquets[chosenBouquet];const content='ДИКО — пожелания к букету\n\nБукет: '+b.name+'\nОриентир по стоимости: '+b.price+'\nНастроение: '+moods[currentMood].word+'\n\nСостав: '+b.composition+'\n\nКому подарить: ____________________\nДата: ____________________\nОсобые пожелания: ____________________\n\nЭто сохранённый выбор для обсуждения с флористом. Заказ не оформлен.\n';const blob=new Blob([content],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='ДИКО — мой букет.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Пожелания сохранены в текстовый файл.');});
const showHero=()=>{heroImage.classList.add('loaded');if(!reducedMotion)animateIn(document.querySelector('.hero-floral-inner'),[{opacity:0,transform:'translateY(180px) rotate(22deg) scale(.7)'},{opacity:1,transform:'translateY(0) rotate(0) scale(1)'}],1600);};
heroImage.addEventListener('load',showHero,{once:true});if(heroImage.complete&&heroImage.naturalWidth)showHero();
if(!reducedMotion){document.body.classList.add('motion-ready');document.querySelectorAll('.hero-line').forEach((line,i)=>line.animate([{opacity:0,transform:'translateY(90px) rotate(4deg)',clipPath:'inset(100% 0 0 0)'},{opacity:1,transform:'translateY(0) rotate(0)',clipPath:'inset(0 0 0 0)'}],{duration:1150,delay:150+i*110,easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'}));document.querySelector('.hero-badge').animate([{opacity:0,transform:'scale(.3) rotate(-100deg)'},{opacity:1,transform:'scale(1) rotate(10deg)'}],{duration:1000,delay:650,easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.reveal,.bouquet-card').forEach(el=>observer.observe(el));}
const floral=document.querySelector('.hero-floral'),hero=document.querySelector('.hero'),manifesto=document.querySelector('.manifesto'),manifestoPhoto=document.querySelector('.manifesto-photo'),orbit=document.querySelector('.manifesto-orbit'),closing=document.querySelector('.closing'),closingFlower=document.querySelector('.closing-flower'),moodImage=document.querySelector('#mood-image'),progress=document.querySelector('.scroll-progress');
let pointer={x:0,y:0},smoothPointer={x:0,y:0},animationFrame=0;
const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
function renderMotion(){animationFrame=0;const y=window.scrollY;const max=document.documentElement.scrollHeight-window.innerHeight;progress.style.transform='scaleX('+(max>0?y/max:0)+')';if(!reducedMotion){smoothPointer.x+=(pointer.x-smoothPointer.x)*.07;smoothPointer.y+=(pointer.y-smoothPointer.y)*.07;const rect=hero.getBoundingClientRect();if(rect.bottom>0){floral.style.transform='translate3d('+smoothPointer.x*18+'px,'+(smoothPointer.y*12+y*.16)+'px,0) rotate('+(smoothPointer.x*3-y*.003)+'deg)';}const mr=manifesto.getBoundingClientRect();if(mr.bottom>0&&mr.top<innerHeight){const mp=clamp(-mr.top/Math.max(1,manifesto.offsetHeight-innerHeight),0,1);manifestoPhoto.style.transform='scale('+(1.16-mp*.14)+') translate3d(0,'+(-mp*35)+'px,0)';orbit.style.transform='rotate('+(12+mp*110)+'deg)';document.querySelectorAll('.manifesto-copy h2 span').forEach((line,i)=>{line.style.transform='translate3d('+(mp*(i===1?-1:1)*25)+'px,0,0)';});}const cr=closing.getBoundingClientRect();if(cr.top<innerHeight&&cr.bottom>0){const cp=clamp((innerHeight-cr.top)/(innerHeight+cr.height),0,1);closingFlower.style.transform='translate3d(0,'+((cp-.5)*90)+'px,0) rotate('+(18+cp*12)+'deg)';}if(currentMood==='love'){const moodRect=document.querySelector('.mood-stage').getBoundingClientRect();if(moodRect.top<innerHeight&&moodRect.bottom>0)moodImage.style.transform='translate3d('+smoothPointer.x*9+'px,'+smoothPointer.y*8+'px,0) rotate('+smoothPointer.x*2+'deg)';}else{moodImage.style.transform='';}if(Math.abs(pointer.x-smoothPointer.x)>.002||Math.abs(pointer.y-smoothPointer.y)>.002)animationFrame=requestAnimationFrame(renderMotion);}}
function scheduleMotion(){if(!animationFrame)animationFrame=requestAnimationFrame(renderMotion);}
window.addEventListener('scroll',scheduleMotion,{passive:true});window.addEventListener('resize',scheduleMotion,{passive:true});window.addEventListener('load',scheduleMotion);
if(finePointer&&!reducedMotion){window.addEventListener('pointermove',event=>{pointer.x=(event.clientX/innerWidth-.5)*2;pointer.y=(event.clientY/innerHeight-.5)*2;scheduleMotion();},{passive:true});document.querySelectorAll('.magnetic').forEach(button=>{button.addEventListener('pointermove',event=>{const rect=button.getBoundingClientRect();const x=(event.clientX-rect.left-rect.width/2)*.18;const y=(event.clientY-rect.top-rect.height/2)*.23;button.style.transform='translate('+x+'px,'+y+'px)';});button.addEventListener('pointerleave',()=>{button.style.transform='';});});document.querySelectorAll('.bouquet-visual').forEach(card=>{card.addEventListener('pointermove',event=>{const rect=card.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width-.5;const y=(event.clientY-rect.top)/rect.height-.5;card.style.transform='perspective(900px) rotateX('+(-y*6)+'deg) rotateY('+(x*7)+'deg)';});card.addEventListener('pointerleave',()=>card.style.transform='');});}
scheduleMotion();
if(document.modelContext?.registerTool){
  const lifecycle=new AbortController();
  const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'list_bouquets',title:'Посмотреть коллекцию букетов',description:'Returns the three bouquets and currently selected mood and bouquet. Does not place an order.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({bouquets:Object.entries(bouquets).map(([id,b])=>({id,name:b.name,price:b.price,composition:b.composition})),mood:currentMood,selected:chosenBouquet})});
  register({name:'set_bouquet_mood',title:'Выбрать настроение букета',description:'Changes the visible mood and bouquet recommendation. No order or external transmission.',inputSchema:{type:'object',properties:{mood:{type:'string',enum:['love','thanks','just']}},required:['mood'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||typeof input!=='object'||!Object.hasOwn(moods,input.mood)||Object.keys(input).some(key=>key!=='mood'))throw new Error('Use mood: love, thanks or just.');setMood(input.mood);return{mood:currentMood,recommendedBouquet:moods[currentMood].bouquet};}});
  register({name:'select_bouquet',title:'Сохранить выбор букета на странице',description:'Stages a bouquet in the visible selection summary. Does not submit an order or payment.',inputSchema:{type:'object',properties:{bouquet:{type:'string',enum:['wild','soft','peony']}},required:['bouquet'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||typeof input!=='object'||!Object.hasOwn(bouquets,input.bouquet)||Object.keys(input).some(key=>key!=='bouquet'))throw new Error('Use bouquet: wild, soft or peony.');selectBouquet(input.bouquet);return{selected:chosenBouquet,name:bouquets[chosenBouquet].name,orderSubmitted:false};}});
  window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
