import { useState, useEffect, useMemo } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useParams, useSearchParams, Link } from 'react-router-dom'
import { useReactTable, getCoreRowModel, flexRender, ColumnDef, VisibilityState, RowSelectionState } from '@tanstack/react-table'
import { Search, Plus, SlidersHorizontal, Download, RefreshCw, Columns3, ChevronLeft, ChevronRight, ArrowUpDown, Star, ExternalLink, Info, FolderPlus, ArrowLeft, Package, Check, GitCompareArrows, X } from 'lucide-react'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts'
import { refresh, api, params, money, num, date, key, Product } from './api'
import { useWorkspace, PageHead, Loading, ErrorState, Empty, ProductName, Source, Change, Available, Modal, FormError, chartColor, PriceTooltip } from './ui'

export function Products(){
 const {dataset,context,tell,openAdd}=useWorkspace(),client=useQueryClient(),[url,setUrl]=useSearchParams()
 const [q,setQ]=useState(url.get('q')||''),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[showFilters,setShowFilters]=useState(false),[columnsOpen,setColumnsOpen]=useState(false),[visible,setVisible]=useState<VisibilityState>({updated_at:false}),[selection,setSelection]=useState<RowSelectionState>({}),[sort,setSort]=useState('updated_at'),[direction,setDirection]=useState('desc'),[action,setAction]=useState(''),[collection,setCollection]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [marketplace,setMarketplace]=useState(''),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState(''),[rating,setRating]=useState(''),[reviews,setReviews]=useState(''),[available,setAvailable]=useState(''),[brand,setBrand]=useState(''),[seller,setSeller]=useState('')
 useEffect(()=>setQ(url.get('q')||''),[url.get('q')])
 const collectionId=url.get('collection_id')||''
 const filter={dataset,context,q: url.get('q')||'',collection_id:collectionId,marketplace,min_price:minPrice,max_price:maxPrice,min_rating:rating,min_reviews:reviews,available,brand,seller,sort,direction,page,page_size:pageSize}
 useEffect(()=>{const timer=setTimeout(()=>{if(q!==(url.get('q')||'')){const next=new URLSearchParams(url);q?next.set('q',q):next.delete('q');setUrl(next,{replace:true});setPage(1)}},300);return()=>clearTimeout(timer)},[q,url,setUrl])
 useEffect(()=>{setSelection({});setPage(1)},[dataset,context,collectionId,marketplace,minPrice,maxPrice,rating,reviews,available,brand,seller,filter.q])
 const query=useQuery({queryKey:['products',filter],queryFn:()=>api('/products'+params(filter)),refetchInterval:20000})
 const collections=useQuery({queryKey:['collections',dataset,context],queryFn:()=>api('/collections'+params({dataset,context}))})
 const selected=query.data?.items.filter((p:Product)=>selection[p.id])||[]
 const selectedIds=selected.map((p:Product)=>p.id)
 const definitions=useMemo<ColumnDef<Product>[]>(()=>[
  {id:'select',header:({table})=><input aria-label="Выбрать страницу" type="checkbox" checked={table.getIsAllRowsSelected()} onChange={table.getToggleAllRowsSelectedHandler()}/>,cell:({row})=><input aria-label={'Выбрать '+row.original.title} type="checkbox" checked={row.getIsSelected()} onChange={row.getToggleSelectedHandler()}/>,enableHiding:false},
  {accessorKey:'title',header:'Товар',cell:({row})=><ProductName product={row.original}/>,enableHiding:false},
  {accessorKey:'marketplace',header:'Площадка',cell:({getValue})=><Source marketplace={getValue() as string}/>},
  {accessorKey:'seller',header:'Продавец',cell:({getValue})=><span className="seller-cell">{getValue() as string||'—'}</span>},
  {accessorKey:'price',header:'Цена',cell:({getValue})=><b className="price-cell">{money(getValue() as number) }</b>},
  {accessorKey:'price_change',header:'Δ цены',cell:({getValue})=><Change value={getValue() as number}/>},
  {accessorKey:'rating',header:'Рейтинг',cell:({getValue})=><span><Star className="rating-star" size={12}/>{getValue()==null?'—':String(getValue())}</span>},
  {accessorKey:'reviews',header:'Отзывы',cell:({getValue})=>num(getValue() as number)},
  {accessorKey:'available',header:'Наличие',cell:({getValue})=><Available value={getValue() as boolean|null}/>},
  {accessorKey:'updated_at',header:'Обновление',cell:({getValue})=>date(getValue() as string)}],[])
 const table=useReactTable({data:query.data?.items||[],columns:definitions,getCoreRowModel:getCoreRowModel(),getRowId:p=>String(p.id),manualPagination:true,manualSorting:true,state:{columnVisibility:visible,rowSelection:selection},onColumnVisibilityChange:setVisible,onRowSelectionChange:setSelection})
 const reset=()=>{setMarketplace('');setMinPrice('');setMaxPrice('');setRating('');setReviews('');setAvailable('');setBrand('');setSeller('');setQ('');setUrl({});setPage(1)}
 return <><PageHead eyebrow="КАТАЛОГ И НАБЛЮДЕНИЯ" title="Товары" subtitle="Сравнивайте карточки и следите за изменениями в вашем ассортименте." actions={<button className="btn primary" onClick={openAdd}><Plus size={17}/>Добавить товары</button>}/><section className="card catalog-card"><div className="catalog-toolbar"><div className="input-icon"><Search size={16}/><input placeholder="Название, бренд или артикул" aria-label="Поиск в каталоге" value={q} onChange={e=>setQ(e.target.value)}/></div><select aria-label="Фильтр подборки" value={collectionId} onChange={e=>{const next=new URLSearchParams(url);e.target.value?next.set('collection_id',e.target.value):next.delete('collection_id');setUrl(next)}}><option value="">Все подборки</option>{collections.data?.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select><button className={'btn '+(showFilters?'pressed':'')} onClick={()=>setShowFilters(!showFilters)}><SlidersHorizontal size={15}/>Фильтры</button><div className="column-menu"><button className="btn icon-btn" aria-label="Выбор колонок" onClick={()=>setColumnsOpen(!columnsOpen)}><Columns3 size={17}/></button>{columnsOpen&&<div className="popover"><b>Отображаемые колонки</b>{table.getAllLeafColumns().filter(c=>c.getCanHide()).map(c=><label className="check-label" key={c.id}><input type="checkbox" checked={c.getIsVisible()} onChange={c.getToggleVisibilityHandler()}/>{String(c.columnDef.header)}</label>)}</div>}</div><a className="btn export-btn" href={'/api/export'+params({...filter,format:'csv',ids:selectedIds.join(',')})}><Download size={15}/>CSV</a></div>
 {showFilters&&<div className="catalog-filters"><label>Площадка<select value={marketplace} onChange={e=>setMarketplace(e.target.value)}><option value="">Все</option><option value="wb">Wildberries</option><option value="ozon">Ozon</option></select></label><label>Цена от<input type="number" min={0} value={minPrice} onChange={e=>setMinPrice(e.target.value)} placeholder="₽"/></label><label>Цена до<input type="number" min={0} value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} placeholder="₽"/></label><label>Рейтинг от<input type="number" min={0} max={5} step="0.1" value={rating} onChange={e=>setRating(e.target.value)}/></label><label>Отзывы от<input type="number" min={0} value={reviews} onChange={e=>setReviews(e.target.value)}/></label><label>Наличие<select value={available} onChange={e=>setAvailable(e.target.value)}><option value="">Любое</option><option value="true">Подтверждено</option><option value="false">Подтверждено отсутствие</option></select></label><label>Бренд<input value={brand} onChange={e=>setBrand(e.target.value)}/></label><label>Продавец<input value={seller} onChange={e=>setSeller(e.target.value)}/></label><button className="text-button" onClick={reset}>Сбросить</button></div>}
 <div className="catalog-meta"><span><b>{num(query.data?.total)}</b> вариантов <span className="small-tag">{dataset==='demo'?'Демо':'Мои данные'}</span></span><span className="muted">{context}</span><div className="mobile-sort"><select aria-label="Сортировка" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated_at">По обновлению</option><option value="price">По цене</option><option value="rating">По рейтингу</option><option value="reviews">По отзывам</option></select><button className="icon-btn" aria-label="Порядок сортировки" onClick={()=>setDirection(direction==='asc'?'desc':'asc')}><ArrowUpDown size={15}/></button></div></div>
 {selectedIds.length>0&&<div className="selection-bar"><b>Выбрано: {selectedIds.length}</b><button onClick={()=>{setAction('collection');setError('')}}><FolderPlus size={15}/>В подборку</button><button onClick={()=>{setAction('refresh');setError('')}}><RefreshCw size={15}/>Обновить</button><a href={'/api/export'+params({...filter,format:'csv',ids:selectedIds.join(',')})}><Download size={15}/>CSV</a><button onClick={()=>setSelection({})} className="icon-btn" aria-label="Снять выбор"><X size={15}/></button></div>}
 {query.isPending?<Loading/>:query.error?<ErrorState error={query.error} retry={()=>query.refetch()}/>:query.data?.items.length?<><div className="table-scroll desktop-products"><table className="product-table"><thead>{table.getHeaderGroups().map(g=><tr key={g.id}>{g.headers.map(h=><th key={h.id}>{['title','price','rating','reviews','updated_at'].includes(h.column.id)?<button onClick={()=>{setSort(h.column.id);setDirection(sort===h.column.id&&direction==='desc'?'asc':'desc')}}>{flexRender(h.column.columnDef.header,h.getContext())}<ArrowUpDown size={11}/></button>:flexRender(h.column.columnDef.header,h.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(r=><tr key={r.id} className={r.getIsSelected()?'selected':''}>{r.getVisibleCells().map(c=><td key={c.id}>{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table></div><div className="mobile-products">{query.data.items.map((p:Product)=><div className="mobile-product" key={p.id}><div><input aria-label={'Выбрать '+p.title} type="checkbox" checked={!!selection[p.id]} onChange={e=>setSelection({...selection,[p.id]:e.target.checked})}/><ProductName product={p}/></div><div className="mobile-product-stats"><Source marketplace={p.marketplace}/><b>{money(p.price)}</b><Change value={p.price_change}/><Available value={p.available}/></div></div>)}</div><div className="pagination"><span>{(page-1)*pageSize+1}–{Math.min(page*pageSize,query.data.total)} из {query.data.total}</span><div><select aria-label="Строк на странице" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1);setSelection({})}}><option value={20}>20 строк</option><option value={50}>50 строк</option><option value={100}>100 строк</option></select><button className="icon-btn" aria-label="Предыдущая страница" disabled={page===1} onClick={()=>{setPage(page-1);setSelection({})}}><ChevronLeft size={17}/></button><span className="page-number">{page}</span><button className="icon-btn" aria-label="Следующая страница" disabled={page*pageSize>=query.data.total} onClick={()=>{setPage(page+1);setSelection({})}}><ChevronRight size={17}/></button></div></div></>:<Empty title="Товары не найдены" description="Измените фильтры или добавьте карточки в выбранном режиме." action={<button className="btn" onClick={reset}>Сбросить фильтры</button>}/>}</section><div className="info-box"><Info size={15}/>Неизвестные цены и остатки отображаются как «—». Ошибка сбора не означает отсутствие товара.</div>
 {action&&<Modal title={action==='collection'?'Добавить в подборку':'Обновить выбранные товары'} close={()=>setAction('')}><p className="modal-intro">Выбрано {selectedIds.length} вариантов · {context} · {dataset==='demo'?'Демо':'Реальные данные'}</p>{action==='collection'?<label>Подборка<select value={collection} onChange={e=>setCollection(e.target.value)}><option value="">Выберите подборку</option>{collections.data?.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>:<div className="info-box">Каждая площадка получит отдельное задание. Источник: {dataset==='demo'?'демо-адаптер':'открытые карточки (сбор не подтверждён)'}. Существующая история сохранится.</div>}<FormError error={error}/><div className="modal-actions"><button className="btn" onClick={()=>setAction('')}>Отмена</button><button className="btn primary" disabled={busy||(action==='collection'&&!collection)} onClick={async()=>{setBusy(true);try{if(action==='collection')await api('/collections/'+collection+'/items',{method:'POST',body:JSON.stringify(selectedIds)});else for(const marketplace of ['wb','ozon']){const ids=selected.filter((p:Product)=>p.marketplace===marketplace).map((p:Product)=>p.id);if(ids.length)await api('/jobs',{method:'POST',body:JSON.stringify({source:dataset==='demo'?'demo':marketplace+'_public',marketplace,dataset,context,variant_ids:ids,limit:500,idempotency_key:key()})})}refresh(client);tell(action==='collection'?'Товары добавлены в подборку':'Задания добавлены в очередь');setAction('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Сохраняем…':action==='collection'?'Добавить':'Запустить обновление'}</button></div></Modal>}</>
}

export function ProductDetail(){
 const {id}=useParams(),{context,dataset,tell}=useWorkspace(),client=useQueryClient(),[tab,setTab]=useState('Обзор'),[busy,setBusy]=useState(false)
 const query=useQuery({queryKey:['product',id,context],queryFn:()=>api('/products/'+id+params({context})),refetchInterval:15000})
 const product=query.data
 if(query.isPending)return <Loading/>
 if(query.error)return <ErrorState error={query.error} retry={()=>query.refetch()}/>
 if(!product)return null
 if(product.dataset!==dataset)return <Empty title="Товар находится в другом режиме данных" description="Переключите Демо / Мои данные в верхней панели."/>
 const stale=new Date(product.updated_at).getTime()<Date.now()-86400000
 return <><Link className="back-link" to="/products"><ArrowLeft size={15}/>Все товары</Link><div className="product-detail-head"><span className="detail-image">{product.image?<img src={product.image} alt={product.title}/>:<Package size={45}/>}</span><div><div className="detail-labels"><Source marketplace={product.marketplace}/><span className="small-tag">{dataset==='demo'?'Демо':product.source}</span>{product.is_own&&<span className="small-tag own-tag">Мой товар</span>}</div><h1>{product.title}</h1><p>{product.external_id} · вариант {product.variant_id} · {product.brand||'Бренд неизвестен'}</p><div className="detail-actions"><button className="btn" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/jobs',{method:'POST',body:JSON.stringify({source:dataset==='demo'?'demo':product.source==='wb_own'?'wb_own':product.marketplace+'_public',marketplace:product.marketplace,dataset,context,variant_ids:[Number(id)],idempotency_key:key()})});tell('Обновление добавлено в очередь')}catch(e){tell((e as Error).message)}finally{setBusy(false)}}}><RefreshCw size={15}/>Обновить</button><button className="btn" onClick={async()=>{try{await api('/products/'+id+params({is_own:!product.is_own}),{method:'PATCH'});refresh(client)}catch(e){tell((e as Error).message)}}}><Check size={15}/>{product.is_own?'Снять отметку «Мой»':'Отметить как свой'}</button>{product.url&&<a className="btn" target="_blank" rel="noreferrer" href={product.url}><ExternalLink size={15}/>Карточка на площадке</a>}</div></div><div className="detail-price"><small>Наблюдаемая цена</small><strong>{money(product.price)}</strong>{product.original_price!=null&&<del>{money(product.original_price)}</del>}<Available value={product.available}/></div></div>
 {stale&&<div className="warning-box">Данные устарели: последнее успешное наблюдение {date(product.updated_at)}.</div>}{product.attempts[0]?.status&&product.attempts[0].status!=='success'&&<div className="warning-box">Последняя попытка: {product.attempts[0].error||product.attempts[0].status}. Сохранённое наличие не изменено.</div>}
 <div className="tabs">{['Обзор','История','Характеристики','Конкуренты','Поисковые позиции','События'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Обзор'&&<><div className="two-col"><section className="card detail-facts"><h2>Данные карточки</h2><dl><dt>Продавец</dt><dd>{product.seller||'—'}</dd><dt>Категория</dt><dd>{product.category||'—'}</dd><dt>Рейтинг</dt><dd><span className="rating-star">★</span> {product.rating??'—'}</dd><dt>Количество отзывов</dt><dd>{num(product.reviews)}</dd><dt>Точные остатки</dt><dd>{product.stock??'—'}</dd><dt>Первое обнаружение</dt><dd>{date(product.first_seen)}</dd><dt>Успешное обновление</dt><dd>{date(product.updated_at)}</dd><dt>Источник</dt><dd>{product.source}</dd><dt>Условия цены</dt><dd>{product.price_condition}</dd><dt>Контекст</dt><dd>{product.context}</dd></dl></section><section className="card detail-facts"><h2>Подборки и качество данных</h2><div className="detail-collections">{product.collections.length?product.collections.map((c:any)=><Link key={c.id} to={'/products?collection_id='+c.id}><FolderPlus size={17}/>{c.name}<ChevronRight size={15}/></Link>):<p className="muted">Нет связанных подборок</p>}</div><h3>Недоступные показатели</h3>{Object.entries(product.missing||{}).map(([k,v])=><p className="missing-reason" key={k}><Info size={15}/>{String(v)}</p>)}</section></div><HistoryCharts product={product}/></>}
 {tab==='История'&&<><HistoryCharts product={product}/><section className="card"><div className="section-head"><h2>Наблюдения</h2><a className="btn" href={'/api/export'+params({dataset,context,scope:'history',format:'csv',ids:id})}><Download size={15}/>История CSV</a></div><div className="table-scroll"><table><thead><tr><th>Время</th><th>Цена</th><th>Отзывы</th><th>Рейтинг</th><th>Наличие</th><th>Источник / контекст</th></tr></thead><tbody>{[...product.observations].reverse().map((s:any)=><tr key={s.id}><td>{date(s.observed_at)}</td><td>{money(s.price)}</td><td>{num(s.reviews)}</td><td>{s.rating??'—'}</td><td><Available value={s.available}/></td><td>{s.source}<small className="block muted">{s.context}</small></td></tr>)}</tbody></table></div></section></>}
 {tab==='Характеристики'&&<section className="card detail-facts"><h2>Характеристики варианта</h2><dl>{Object.entries(product.characteristics||{}).map(([k,v])=><div className="contents" key={k}><dt>{k}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v??'—')}</dd></div>)}</dl></section>}
 {tab==='Конкуренты'&&<section className="card">{product.groups.length?product.groups.map((g:any)=><Link className="leader-row" key={g.id} to="/competitors"><GitCompareArrows size={19}/><b>{g.name}</b><ChevronRight size={16}/></Link>):<Empty title="Сравнения ещё не созданы" action={<Link className="btn" to="/competitors">Создать группу сравнения</Link>}/>}</section>}
 {tab==='Поисковые позиции'&&<section className="card"><div className="section-head"><h2>Наблюдаемые позиции</h2></div><div className="table-scroll"><table><thead><tr><th>Запрос</th><th>Время</th><th>Позиция</th><th>Контекст</th></tr></thead><tbody>{product.positions.map((r:any,i:number)=><tr key={i}><td>{r.query}</td><td>{date(r.date)}</td><td>{r.position??`Не найден среди первых ${r.depth} результатов`}</td><td>{r.context}</td></tr>)}</tbody></table></div>{!product.positions.length&&<Empty title="Нет поисковых наблюдений"/>}<div className="chart-foot">Выдача зависит от времени, региона и контекста сбора. Рекламные размещения не классифицированы.</div></section>}
 {tab==='События'&&<section className="card"><div className="section-head"><h2>Изменения карточки</h2></div>{product.events.length?product.events.map((e:any)=><div className="event-row" key={e.id}><span className="event-dot"/><div><b>{e.title}</b><p>{e.old_value??'—'} → {e.new_value??'—'}</p></div><time>{date(e.created_at)}</time></div>):<Empty title="Изменений ещё нет"/>}</section>}
 </>
}

function HistoryCharts({product}:{product:any}){return <div className="two-col history-charts">{[{key:'price',title:'История цены',color:chartColor[0],unit:'₽'},{key:'reviews',title:'Количество отзывов',color:chartColor[1],unit:'шт.'},{key:'rating',title:'Изменение рейтинга',color:chartColor[2],unit:''},{key:'available',title:'История наличия',color:chartColor[3],unit:''}].map(metric=><section className="card" key={metric.key}><div className="section-head"><div><h2>{metric.title}</h2><p>{product.aggregation} · {product.context}</p></div></div><div className="chart"><ResponsiveContainer><LineChart data={product.history.map((h:any)=>({...h,available:h.available===null?null:h.available?1:0}))} margin={{left:-15,right:20}}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="date" tickFormatter={v=>new Date(v).toLocaleDateString('ru-RU',{day:'numeric',month:'short'})} minTickGap={35} tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis domain={metric.key==='available'?[0,1]:['auto','auto']} tick={{fontSize:10}} tickFormatter={metric.key==='available'?v=>v===1?'Да':v===0?'Нет':'':undefined} axisLine={false} tickLine={false}/><Tooltip formatter={v=>metric.key==='price'?money(Number(v)):metric.key==='available'?v===1?'В наличии':'Нет в наличии':num(Number(v))}/><Line type={metric.key==='available'?'stepAfter':'monotone'} dataKey={metric.key} name={metric.title} stroke={metric.color} dot={false} strokeWidth={2} connectNulls={false}/></LineChart></ResponsiveContainer></div><div className="chart-foot">Источник: {product.source} · неизвестные значения не заменяются нулём</div></section>)}</div>}


